import Head from "next/head";

import Header from "./header";
export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Prafulla Pal | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <div className="max-w-screen-xl flex flex-col items-center justify-between mx-auto">{children}</div>
    </>
  );
}
